# SPDX-License-Identifier: Apache-2.0
# Copyright 2026 Ivan Pinatti
"""Tests for `hash_locked_requirements`, the file level grammar.

They run in process rather than through the command line, because the one
thing this grammar does that no other does is ask PyPI, and the fetch has to
be stubbed: nothing in this suite touches the network. Every diff is still
built against a real base file with a real `index` line, since the grammar
reads both sides whole and refuses a file whose base it cannot prove.
"""

import difflib
import io
import json
import sys
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

# E402: the import has to follow the sys.path line above.
import pin_only  # noqa: E402

LOCK = "tests/requirements.txt"
SOURCE = "tests/requirements.in"

CONFIG = f"""\
allowed_paths:
  - {LOCK}
  - {SOURCE}
rules:
  - path: "*requirements.txt"
    grammars: [hash_locked_requirements]
  - path: "*requirements.in"
    grammars: [requirement_line]
"""

HEADER = (
    "# This file was autogenerated by uv via the following command:\n"
    "#    uv pip compile --generate-hashes --python-version=3.14 "
    "--exclude-newer=P7D --output-file=requirements.txt requirements.in\n"
)


def _hash(n: int) -> str:
    return f"{n:064x}"


def _entry(name: str, version: str, hashes: list[int], via: str) -> str:
    lines = [f"{name}=={version} \\"]
    lines += [f"    --hash=sha256:{_hash(n)} \\" for n in hashes[:-1]]
    lines.append(f"    --hash=sha256:{_hash(hashes[-1])}")
    return "\n".join(lines) + "\n" + via


BASE = (
    HEADER
    + _entry("iniconfig", "2.1.0", [1, 2], "    # via pytest\n")
    + _entry("pytest", "9.1.1", [3, 4], "    # via -r requirements.in\n")
)
HEAD = (
    HEADER
    + _entry("iniconfig", "2.1.0", [1, 2], "    # via pytest\n")
    + _entry(
        "pytest",
        "9.2.0",
        [5, 6, 7],
        "    # via\n    #   -r requirements.in\n",
    )
)


def _file_diff(path: str, before: str, after: str) -> str:
    """A `git diff` style section for one file, with the base's blob id."""
    old = pin_only._git_blob_id(before.encode())
    new = pin_only._git_blob_id(after.encode())
    body = difflib.unified_diff(
        before.splitlines(),
        after.splitlines(),
        f"a/{path}",
        f"b/{path}",
        lineterm="",
    )
    return (
        f"diff --git a/{path} b/{path}\n"
        f"index {old[:12]}..{new[:12]} 100644\n" + "\n".join(body) + "\n"
    )


def _repo(tmp_path: Path, files: dict[str, str], config: str = CONFIG) -> Path:
    (tmp_path / ".github").mkdir(exist_ok=True)
    (tmp_path / ".github" / "pin-only.yml").write_text(config)
    for path, text in files.items():
        target = tmp_path / path
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(text)
    return tmp_path


@pytest.fixture
def published(monkeypatch):
    """Stub PyPI with a table of release hashes, recording every query."""
    table: dict[tuple[str, str], object] = {}
    calls: list[tuple[str, str]] = []

    def fake(name: str, version: str) -> frozenset[str]:
        calls.append((name, version))
        answer = table.get((name, version), frozenset())
        if isinstance(answer, Exception):
            raise answer
        return answer

    monkeypatch.setattr(pin_only, "_pypi_sha256s", fake)
    table["calls"] = calls
    return table


def _run(monkeypatch, capsys, root: Path, diff: str) -> tuple[int, str]:
    monkeypatch.setattr(sys, "stdin", io.StringIO(diff))
    code = pin_only.main(["--repo-root", str(root)])
    return code, capsys.readouterr().out


def _bump(tmp_path, before=BASE, after=HEAD) -> tuple[Path, str]:
    root = _repo(tmp_path, {LOCK: before})
    return root, _file_diff(LOCK, before, after)


# ---------------------------------------------------------------------------
# Accepted
# ---------------------------------------------------------------------------


def test_accepts_a_bump_with_published_hashes(tmp_path, monkeypatch, capsys, published):
    published[("pytest", "9.2.0")] = frozenset(_hash(n) for n in (5, 6, 7, 8))
    source_before = "pytest==9.1.1\n"
    source_after = "pytest==9.2.0\n"
    root = _repo(tmp_path, {LOCK: BASE, SOURCE: source_before})
    diff = _file_diff(LOCK, BASE, HEAD) + _file_diff(
        SOURCE, source_before, source_after
    )

    code, out = _run(monkeypatch, capsys, root, diff)

    assert code == 0, out
    # Only the package that moved is looked up; iniconfig is unchanged.
    assert published["calls"] == [("pytest", "9.2.0")]


def test_checks_hashes_that_changed_without_a_version_change(
    tmp_path, monkeypatch, capsys, published
):
    after = BASE.replace(f"sha256:{_hash(2)}", f"sha256:{_hash(9)}")
    published[("iniconfig", "2.1.0")] = frozenset({_hash(1), _hash(9)})
    root, diff = _bump(tmp_path, BASE, after)

    code, out = _run(monkeypatch, capsys, root, diff)

    assert code == 0, out
    assert published["calls"] == [("iniconfig", "2.1.0")]


def test_accepts_extras_and_markers_that_stay_put(
    tmp_path, monkeypatch, capsys, published
):
    marker = ' ; python_version >= "3.10"'
    before = HEADER + _entry("rich[jupyter]", "14.0.0" + marker, [1], "")
    after = HEADER + _entry("rich[jupyter]", "14.1.0" + marker, [2], "")
    published[("rich", "14.1.0")] = frozenset({_hash(2)})
    root, diff = _bump(tmp_path, before, after)

    code, out = _run(monkeypatch, capsys, root, diff)

    assert code == 0, out


# ---------------------------------------------------------------------------
# Refused
# ---------------------------------------------------------------------------


def test_refuses_a_hash_pypi_does_not_publish(tmp_path, monkeypatch, capsys, published):
    published[("pytest", "9.2.0")] = frozenset(_hash(n) for n in (5, 6))
    root, diff = _bump(tmp_path)

    code, out = _run(monkeypatch, capsys, root, diff)

    assert code == 1
    assert "pytest==9.2.0 carries 1 hash(es) PyPI does not publish" in out
    assert _hash(7) in out


@pytest.mark.parametrize(
    "error", [OSError("network is unreachable"), ValueError("not JSON")]
)
def test_refuses_when_pypi_cannot_confirm(
    tmp_path, monkeypatch, capsys, published, error
):
    published[("pytest", "9.2.0")] = error
    root, diff = _bump(tmp_path)

    code, out = _run(monkeypatch, capsys, root, diff)

    assert code == 1
    assert "could not confirm pytest==9.2.0's hashes with PyPI" in out
    assert str(error) in out


def test_refuses_an_added_package(tmp_path, monkeypatch, capsys, published):
    after = HEAD + _entry("pluggy", "1.6.0", [8], "    # via pytest\n")
    root, diff = _bump(tmp_path, BASE, after)

    code, out = _run(monkeypatch, capsys, root, diff)

    assert code == 1
    assert "adds package pluggy, which is not a version bump" in out
    assert published["calls"] == []


def test_refuses_a_removed_package(tmp_path, monkeypatch, capsys, published):
    after = HEADER + _entry("pytest", "9.2.0", [5], "")
    root, diff = _bump(tmp_path, BASE, after)

    code, out = _run(monkeypatch, capsys, root, diff)

    assert code == 1
    assert "removes package iniconfig, which is not a version bump" in out


def test_refuses_a_changed_marker_as_a_different_package(
    tmp_path, monkeypatch, capsys, published
):
    before = HEADER + _entry("rich", "14.0.0", [1], "")
    after = HEADER + _entry("rich", '14.0.0 ; sys_platform == "linux"', [1], "")
    root, diff = _bump(tmp_path, before, after)

    code, out = _run(monkeypatch, capsys, root, diff)

    assert code == 1
    assert 'adds package rich ; sys_platform == "linux"' in out
    assert "removes package rich," in out


@pytest.mark.parametrize(
    "after",
    [
        # An index option slipped in above the packages.
        HEAD.replace(HEADER, HEADER + "--extra-index-url https://example.test/\n"),
        # The recorded command changed.
        HEAD.replace("--exclude-newer=P7D ", ""),
        # The packages swapped places.
        HEADER
        + _entry("pytest", "9.2.0", [5], "")
        + _entry("iniconfig", "2.1.0", [1, 2], ""),
    ],
    ids=["option", "header", "order"],
)
def test_refuses_a_change_outside_versions_and_hashes(
    tmp_path, monkeypatch, capsys, published, after
):
    root, diff = _bump(tmp_path, BASE, after)

    code, out = _run(monkeypatch, capsys, root, diff)

    assert code == 1
    assert "changes something other than a version, its hashes" in out
    assert published["calls"] == []


@pytest.mark.parametrize(
    ("after", "reason"),
    [
        (HEAD + "requests\n", "not pinned with `==` and hashes: requests"),
        (HEAD + "requests==2.32.0\n", "not pinned with `==` and hashes"),
        (HEAD + "requests>=2 \\\n    --hash=sha256:" + _hash(1) + "\n", "not pinned"),
        (
            HEAD + "requests==2.32.0 \\\n# sneaky\n    --hash=sha256:" + _hash(1),
            "a comment inside a continued line",
        ),
        (HEAD + "requests==2.32.0 \\\n", "the file ends inside a continued line"),
    ],
    ids=["unpinned", "unhashed", "range", "comment", "dangling"],
)
def test_refuses_a_file_that_is_not_a_lock(
    tmp_path, monkeypatch, capsys, published, after, reason
):
    root, diff = _bump(tmp_path, BASE, after)

    code, out = _run(monkeypatch, capsys, root, diff)

    assert code == 1
    assert reason in out


def test_refuses_when_the_base_cannot_be_proven(
    tmp_path, monkeypatch, capsys, published
):
    # main has moved on since the branch: the checkout's copy is not the
    # diff's base, so neither side can be read whole.
    root, diff = _bump(tmp_path)
    (root / LOCK).write_text(BASE + "# edited on main since\n")

    code, out = _run(monkeypatch, capsys, root, diff)

    assert code == 1
    assert f"{LOCK}: its base on main could not be proven" in out
    assert published["calls"] == []


def test_a_path_outside_the_allowlist_is_never_looked_up(
    tmp_path, monkeypatch, capsys, published
):
    config = CONFIG.replace(f"  - {LOCK}\n", "")
    root = _repo(tmp_path, {LOCK: BASE}, config)

    code, out = _run(monkeypatch, capsys, root, _file_diff(LOCK, BASE, HEAD))

    assert code == 1
    assert f"{LOCK}: not a dependency pin file" in out
    assert published["calls"] == []


# ---------------------------------------------------------------------------
# Helpers and configuration
# ---------------------------------------------------------------------------


def test_no_hash_locked_paths_reads_nothing():
    assert pin_only._hash_locked_problems(["not a diff"], set()) == []


def test_is_hash_locked_needs_a_matching_rule():
    config = pin_only.Config(
        rules=(
            pin_only.PathRule(
                match="*requirements.txt",
                grammars=(pin_only.Grammar(pin_only.HASH_LOCKED),),
            ),
        )
    )
    assert pin_only._is_hash_locked("requirements.txt", config)
    assert not pin_only._is_hash_locked("Dockerfile", config)


@pytest.mark.parametrize(
    ("config", "message"),
    [
        (
            "allowed_paths: [a]\ndefault_grammars: [hash_locked_requirements]\n",
            "not in default_grammars",
        ),
        (
            "allowed_paths: [a]\nrules:\n  - path: a\n"
            "    grammars: [hash_locked_requirements, requirement_line]\n",
            "the only grammar of its rule",
        ),
        (
            "allowed_paths: [a]\nrules:\n  - path: a\n    raw: true\n"
            "    grammars: [hash_locked_requirements]\n",
            "without `raw` (a)",
        ),
    ],
    ids=["default", "shared", "raw"],
)
def test_configuration_keeps_the_grammar_alone(tmp_path, config, message):
    path = tmp_path / "pin-only.yml"
    path.write_text(config)
    with pytest.raises(SystemExit) as raised:
        pin_only.load_config(path, tmp_path)
    assert message in str(raised.value)


class _Response(io.BytesIO):
    def __enter__(self):
        return self

    def __exit__(self, *exc):
        self.close()


def test_pypi_lookup_reads_every_file_digest(monkeypatch):
    seen = {}

    def fake_urlopen(request, timeout):
        seen["url"] = request.full_url
        seen["timeout"] = timeout
        body = {"urls": [{"digests": {"sha256": "aa"}}, {"digests": {"sha256": "bb"}}]}
        return _Response(json.dumps(body).encode())

    monkeypatch.setattr(pin_only.urllib.request, "urlopen", fake_urlopen)

    assert pin_only._pypi_sha256s("zope.interface", "7.0+local") == {"aa", "bb"}
    assert seen == {
        "url": "https://pypi.org/pypi/zope.interface/7.0%2Blocal/json",
        "timeout": 30,
    }


@pytest.mark.parametrize(
    "body",
    [{"info": {}}, {"urls": [{"digests": {}}]}, {"urls": None}],
    ids=["no-urls", "no-sha256", "null"],
)
def test_pypi_lookup_refuses_an_unexpected_answer(monkeypatch, body):
    monkeypatch.setattr(
        pin_only.urllib.request,
        "urlopen",
        lambda request, timeout: _Response(json.dumps(body).encode()),
    )
    with pytest.raises(ValueError, match="unexpected answer from PyPI"):
        pin_only._pypi_sha256s("pytest", "9.2.0")
